interface {	
	name = "simpleIdl",
	methods = {
		foo = {resulttype = "string",
		 	args = {{ direction = "in", type = "string"}}

		},
		cast = { 
			resulttype = "double",
			args = {
				{ direction = "in", type = "double" },
				{ direction = "in", type = "double" }
			}
		},
		boo = {
			resulttype = "string",
			args = {
				{ direction = "in", type = "double" },
				{ direction = "in", type = "double" },
				{ direction = "in", type = "string" },
				{ direction = "out", type = "double" }
			}
		},
		voidFunc = {
			resulttype = "void",
			args = {
				{ direction = "in", type = "char" }
			}
		},
		voidFunc2 = {
			resulttype = "void",
			args = {
				{ direction = "in", type = "void" }
			}
		}
	}		
}
