interface {	
	name = "simpleIdl",
	methods = {
		foo = {resulttype = "string",
		 	args = {{ direction = "in", type = "string"}}

		},
		cast = { 
			resulttype = "double",
			args = {
				{ direction = "in", type = "string" },
				{ direction = "in", type = "double" }
			}
		}
	}		
}
